[package]
name = "kmoddep"
version = "0.1.3"
edition = "2021"
license = "Apache-2.0"
description = "Linux module information"
homepage = "https://github.com/isbm/kmoddep"
repository = "https://github.com/isbm/kmoddep"
readme = "README.md"

[dependencies]
